steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - ${_FUNWATER}
  - --region=${_REGION}
  - --source=${_SOURCE}
  - --entry-point=${_ENTRY_POINT}
  - --trigger-http
  - --runtime=nodejs8
  - --memory=128MB
  - --set-env-vars=IMAGE_URL=${_IMAGE_URL}
  - --set-env-vars=GOOGLE_API_KEY=${_GOOGLE_API_KEY}
  - --set-env-vars=ALGOLIA_APP_ID=${_ALGOLIA_APP_ID}
  - --set-env-vars=ALGOLIA_APP_KEY=${_ALGOLIA_APP_KEY}
  - --set-env-vars=ALGOLIA_APP_INDEX=${_ALGOLIA_APP_INDEX}